In [307]:
import numpy as np

def testcreate(n,val):
    A = np.arange(val,val+n*n).reshape(n,n)
    A = np.sqrt(A)
    bs = [(A[0,:])**2.1]
    print('A :', A)
    print('bs: ', bs)
    return A, bs


In [308]:
import numpy as np
solutions = []
I = np.identity(4)
for x in range(4):
    def testcreate(n,val):
        A = np.arange(val,val+n*n).reshape(n,n)
        A = np.sqrt(A)
        # no need to trasnpose the unit matrix
        bs = I[x]
        return A, bs

    def forsub(L, bs):
        n = 4
        xs = np.zeros(n)
        for i in range(n):
            xs[i] = (bs[i] - L[i,:i]@xs[:i])/L[i,i]
        return xs

    def backsub(U, bs):
        n = 4
        xs = np.zeros(n)
        for i in reversed(range(n)):
            xs[i] = (bs[i] - U[i,i+1:]@xs[i+1:])/U[i,i]
        return xs

    def testsolve(f, A, bs):
        xs = f(A,bs)
        for element in xs:
            solutions.append(element)
        xs = np.linalg.inv(A)
        if x == 3:
            print("np.linalg.inv: \n", xs)

    def ludec(A):
        n = A.shape[0]
        U = np.copy(A)
        L = np.identity(n)

        for j in range(n-1):
            for i in range(j+1,n):
                coeff = U[i,j]/U[j,j]
                U[i,j:] -= coeff*U[j,j:]
                L[i,j] = coeff

        return L, U

    def lusolve(A, bs):
        L, U = ludec(A)
        ys = forsub(L,bs)
        xs = backsub(U,ys)
        return xs

    if __name__ == '__main__':
        A, bs = testcreate(4,21)
        testsolve(lusolve,A,bs)

solutions = np.array(solutions).reshape(4,4)
solutions = solutions.transpose()
print('Mauro \n', solutions)

w, v = np.linalg.eig(A)

for index, element in enumerate(w):
    print('Eigenvalue:', element, ' with eigenvector', v[index])
    print('====================================================')

w, v = np.linalg.eig(solutions)

for index, element in enumerate(w):
    print('Eigenvalue:', element, ' with eigenvector', v[index])
    print('====================================================')

np.linalg.inv: 
 [[ -428980.4369783   1637250.28239776 -2014582.43175401   805708.56468281]
 [ 1354917.34023694 -5189903.4051218   6403036.8758538  -2566061.85641496]
 [-1424042.66985607  5473024.90152475 -6769071.01647551  2717913.05891079]
 [  498099.53522575 -1920343.61557472  2380576.52878968  -957541.59679402]]
Mauro 
 [[ -428980.43546836  1637250.27661743 -2014582.42462556   805708.56182695]
 [ 1354917.33545168 -5189903.386803    6403036.85326262 -2566061.84736429]
 [-1424042.66481087  5473024.88221084 -6769070.99265713  2717913.04936848]
 [  498099.53345588 -1920343.60879937  2380576.52043416  -957541.59344657]]
Eigenvalue: 21.31666266345205  with eigenvector [ 0.44439562 -0.71207238 -0.51532474  0.20536846]
Eigenvalue: -0.06723371479665197  with eigenvector [ 0.48218122 -0.1981024   0.59247232 -0.65201842]
Eigenvalue: -6.930226390419637e-05  with eigenvector [0.51720906 0.24202361 0.39774447 0.68859348]
Eigenvalue: -7.501283436562824e-08  with eigenvector [ 0.55000781  0.628596