In [74]:
import numpy as np

def testcreate(n,val):
    A = np.arange(val,val+n*n).reshape(n,n)
    A = np.sqrt(A)
    bs = (A[0,:])**2.1
    return A, bs

def mag(xs):
    return np.sqrt(np.sum(xs*xs))


def power(A):
    # I set the value of the right side of equation 2 to be equal to the value found in Derivatives I
    mechanical_error = 2.2* 10 ** -16
    zs = np.ones(A.shape[0])
    qs = zs/mag(zs)
    qs_1 = np.zeros(qs.shape)

    for elements in range(len(qs)):
        zs = A @ qs
        qs = zs / mag(zs)
        new_value = abs(qs[elements] - qs_1[elements]) / qs[elements]
        print(qs_1, qs)
        if new_value <= mechanical_error:
            break

        qs_1 = qs



    lam = qs@A@qs

    return lam, qs

def testeigone(f,A,indx=0):
    eigval, eigvec = f(A)
    print(" "); print(eigval); print(eigvec)
    npeigvals, npeigvecs = np.linalg.eig(A)
    print(" ")
    print(npeigvals[indx]); print(npeigvecs[:,indx])


if __name__ == '__main__':
    A, bs = testcreate(4,21)
    testeigone(power,A)

[0. 0. 0. 0.] [0.44421209 0.48212489 0.51726163 0.55015599]
[0.44421209 0.48212489 0.51726163 0.55015599] [0.4443962  0.4821814  0.5172089  0.55000734]
[0.4443962  0.4821814  0.5172089  0.55000734] [0.44439562 0.48218122 0.51720907 0.55000781]
[0.44439562 0.48218122 0.51720907 0.55000781] [0.44439562 0.48218122 0.51720906 0.55000781]
 
21.31666266346187
[0.44439562 0.48218122 0.51720906 0.55000781]
 
21.31666266345205
[0.44439562 0.48218122 0.51720906 0.55000781]
